<?php

namespace rikudou\EuQrPayment\Sepa;

/**
 * @see https://www.iso20022.org/sites/default/files/HomeDocuments/ExternalCodeSets_2Q2018_August2018_v2.xls
 */
class Purpose
{

	// Bank Debt
	const BANK_LOAN_DELAYED_DRAW_FUNDING = 'BKDF';
	const BANK_LOAN_FEES = 'BKFE';
	const BANK_LOAN_FUNDING_MEMO = 'BKFM';
	const BANK_LOAN_ACCRUED_INTEREST_PAYMENT = 'BKIP';
	const BANK_LOAN_PRINCIPAL_PAYDOWN = 'BKPP';

	// Card Settlement
	const CARD_BULK_CLEARING = 'CBLK';
	const CARD_PAYMENT_WITH_CASH_BACK = 'CDCB';
	const CASH_DISBURSEMENT = 'CDCD';
	const CASH_DISBURSEMENT_WITH_SURCHARGING = 'CDCS';
	const CARD_DEFERRED_PAYMENT = 'CDDP';
	const ORIGINAL_CREDIT = 'CDOC';
	const QUASI_CASH = 'CDQC';
	const E_PURSE_TOP_UP = 'ETUP';
	const FEE_COLLECTION = 'FCOL';
	const MOBILE_TOP_UP = 'MTUP';

	// Cash Mgmt
	const ACCOUNT_MANAGEMENT = 'ACCT';
	const CASH_MANAGEMENT_TRANSFER = 'CASH';
	const COLLECTION_PAYMENT = 'COLL';
	const CASH_MGMT_CASH_DISBURSEMENT = 'CSDB';
	const DEPOSIT = 'DEPT';
	const INTRA_COMPANY_PAYMENT = 'INTC';
	const LIQUIDITY_MANAGEMENT = 'LIMA';
	const NETTING = 'NETT';

	// Collateral
	const BOND_FORWARD = 'BFWD';
	const CROSS_CURRENCY_IRS = 'CCIR';
	const CCP_CLEARED_INITIAL_MARGIN = 'CCPC';
	const CCP_CLEARED_VARIATION_MARGIN = 'CCPM';
	const CCP_CLEARED_INITIAL_MARGIN_SEGREGATED_CASH = 'CCSM';
	const CREDIT_DEFAULT_SWAP = 'CRDS';
	const CROSS_PRODUCT = 'CRPR';
	const CREDIT_SUPPORT = 'CRSP';
	const CREDIT_LINE = 'CRTL';
	const EQUITY_OPTION = 'EQPT';
	const EQUITY_SWAP = 'EQUS';
	const EXOTIC_OPTION = 'EXPT';
	const EXCHANGE_TRADED_DERIVATIVES = 'EXTD';
	const FIXED_INCOME = 'FIXI';
	const FORWARD_BROKER_OWNED_CASH_COLLATERAL = 'FWBC';
	const FORWARD_CLIENT_OWNED_CASH_COLLATERAL = 'FWCC';
	const FORWARD_BROKER_OWNED_CASH_COLLATERAL_SEGREGATED = 'FWSB';
	const FORWARD_CLIENT_OWNED_SEGREGATED_CASH_COLLATERAL = 'FWSC';
	const DAILY_MARGIN_ON_LISTED_DERIVATIVES = 'MARG';
	const MBS_BROKER_OWNED_CASH_COLLATERAL = 'MBSB';
	const MBS_CLIENT_OWNED_CASH_COLLATERAL = 'MBSC';
	const FUTURES_INITIAL_MARGIN = 'MGCC';
	const FUTURES_INITIAL_MARGIN_CLIENT_OWNED_SEGREGATED_CASH_COLLATERAL = 'MGSC';
	const CLIENT_OWNED_OCC_PLEDGED_COLLATERAL = 'OCCC';
	const OTC_OPTION_BROKER_OWNED_CASH_COLLATERAL = 'OPBC';
	const OTC_OPTION_CLIENT_OWNED_CASH_COLLATERAL = 'OPCC';
	const OTC_OPTION_BROKER_OWNED_SEGREGATED_CASH_COLLATERAL = 'OPSB';
	const OTC_OPTION_CLIENT_OWNED_CASH_SEGREGATED_CASH_COLLATERAL = 'OPSC';
	const FX_OPTION = 'OPTN';
	const OTC_DERIVATIVES = 'OTCD';
	const REPURCHASE_AGREEMENT = 'REPO';
	const BILATERAL_REPO_BROKER_OWNED_COLLATERAL = 'RPBC';
	const REPO_CLIENT_OWNED_COLLATERAL = 'RPCC';
	const BILATERAL_REPO_BROKER_OWNED_SEGREGATED_CASH_COLLATERAL = 'RPSB';
	const BILATERAL_REPO_CLIENT_OWNED_SEGREGATED_CASH_COLLATERAL = 'RPSC';
	const REVERSE_REPURCHASE_AGREEMENT = 'RVPO';
	const SECURITIES_BUY_SELL_SELL_BUY_BACK = 'SBSC';
	const SINGLE_CURRENCY_IRS_EXOTIC = 'SCIE';
	const SINGLE_CURRENCY_IRS = 'SCIR';
	const SECURITIES_CROSS_PRODUCTS = 'SCRP';
	const BROKER_OWNED_COLLATERAL_SHORT_SALE = 'SHBC';
	const CLIENT_OWNED_COLLATERAL_SHORT_SALE = 'SHCC';
	const SHORT_SELL = 'SHSL';
	const SECURITIES_LENDING_AND_BORROWING = 'SLEB';
	const SECURED_LOAN = 'SLOA';
	const SWAP_BROKER_OWNED_CASH_COLLATERAL = 'SWBC';
	const SWAP_CLIENT_OWNED_CASH_COLLATERAL = 'SWCC';
	const SWAPTION = 'SWPT';
	const SWAPS_BROKER_OWNED_SEGREGATED_CASH_COLLATERAL = 'SWSB';
	const SWAPS_CLIENT_OWNED_SEGREGATED_CASH_COLLATERAL = 'SWSC';
	const TO_BE_ANNOUNCED = 'TBAS';
	const TBA_BROKER_OWNED_CASH_COLLATERAL = 'TBBC';
	const TBA_CLIENT_OWNED_CASH_COLLATERAL = 'TBCC';
	const TREASURY_CROSS_PRODUCT = 'TRCP';

	// Commercial
	const AGRICULTURAL_TRANSFER = 'AGRT';
	const ACCOUNTS_RECEIVABLES_ENTRY = 'AREN';
	const BUSINESS_EXPENSES = 'BEXP';
	const BACK_OFFICE_CONVERSION_ENTRY = 'BOCE';
	const COMMERCIAL_PAYMENT = 'COMC';
	const COPYRIGHT = 'CPYR';
	const PURCHASE_SALE_OF_GOODS = 'GDDS';
	const PURCHASE_SALE_OF_GOODS_AND_SERVICES = 'GDSV';
	const PURCHASE_SALE_OF_GOODS_AND_SERVICES_WITH_CASH_BACK = 'GSCB';
	const LICENSE_FEE = 'LICF';
	const MOBILE_P_B_PAYMENT = 'MP2B';
	const POINT_OF_PURCHASE_ENTRY = 'POPE';
	const ROYALTIES = 'ROYA';
	const PURCHASE_SALE_OF_SERVICES = 'SCVE';
	const SERVICE_CHARGES = 'SERV';
	const SUBSCRIPTION = 'SUBS';
	const SUPPLIER_PAYMENT = 'SUPP';
	const TRADE_SERVICES = 'TRAD';

	// Consumer
	const CHARITY_PAYMENT = 'CHAR';
	const CONSUMER_THIRD_PARTY_CONSOLIDATED_PAYMENT = 'COMT';
	const MOBILE_P_P_PAYMENT = 'MP2P';

	// E-Commerce
	const GUARANTEED_EPAYMENT = 'ECPG';
	const EPAYMENT_RETURN = 'ECPR';
	const NON_GUARANTEED_EPAYMENT = 'ECPU';
	const EPAYMENT = 'EPAY';

	// Finance
	const CAR_LOAN_PRINCIPAL_REPAYMENT = 'CLPR';
	const COMPENSATION_PAYMENT = 'COMP';
	const DEBIT_COLLECTION_PAYMENT = 'DBTC';
	const GOVERNMENT_INSURANCE = 'GOVI';
	const HOUSING_LOAN_REPAYMENT = 'HLRP';
	const HOME_LOAN_SETTLEMENT = 'HLST';
	const INSURANCE_PREMIUM_CAR = 'INPC';
	const INSURANCE_PREMIUM_REFUND = 'INPR';
	const PAYMENT_OF_INSURANCE_CLAIM = 'INSC';
	const INSURANCE_PREMIUM = 'INSU';
	const INTEREST = 'INTE';
	const LABOR_INSURANCE = 'LBRI';
	const LIFE_INSURANCE = 'LIFI';
	const LOAN = 'LOAN';
	const LOAN_REPAYMENT = 'LOAR';
	const PAYMENT_BASED_ON_ENFORCEMENT_ORDER = 'PENO';
	const PROPERTY_INSURANCE = 'PPTI';
	const RENTAL_LEASE_GENERAL = 'RELG';
	const RECURRING_INSTALLMENT_PAYMENT = 'RINP';
	const TRUST_FUND = 'TRFD';

	// Foreign Exchange
	const FORWARD_FOREIGN_EXCHANGE = 'FORW';
	const FOREIGN_EXCHANGE_RELATED_NETTING = 'FXNT';

	// General
	const ADMINISTRATIVE_MANAGEMENT = 'ADMG';
	const ADVANCE_PAYMENT = 'ADVA';
	const BEARER_CHEQUE_DOMESTIC = 'BCDM';
	const BEARER_CHEQUE_FOREIGN = 'BCFG';
	const BUILDING_MAINTENANCE = 'BLDM';
	const BOND_FORWARD_NETTING = 'BNET';
	const CAPITAL_BUILDING = 'CBFF';
	const CAPITAL_BUILDING_RETIREMENT = 'CBFR';
	const CREDIT_CARD_PAYMENT = 'CCRD';
	const CREDIT_CARD_BILL = 'CDBL';
	const CANCELLATION_FEE = 'CFEE';
	const CARD_GENERATED_DIRECT_DEBIT = 'CGDD';
	const TRADE_SETTLEMENT_PAYMENT = 'CORT';
	const COSTS = 'COST';
	const CARPARK_CHARGES = 'CPKC';
	const DEBIT_CARD_PAYMENT = 'DCRD';
	const PRINTED_ORDER_DISBURSEMENT = 'DSMT';
	const DELIVER_AGAINST_PAYMENT = 'DVPM';
	const EDUCATION = 'EDUC';
	const FACTOR_UPDATE_RELATED_PAYMENT = 'FACT';
	const FINANCIAL_AID_IN_CASE_OF_NATURAL_DISASTER = 'FAND';
	const LATE_PAYMENT_OF_FEES_CHARGES = 'FCPM';
	const PAYMENT_OF_FEES = 'FEES';
	const GOVERNMENT_PAYMENT = 'GOVT';
	const IRREVOCABLE_CREDIT_CARD_PAYMENT = 'ICCP';
	const IRREVOCABLE_DEBIT_CARD_PAYMENT = 'IDCP';
	const INSTALMENT_HIRE_PURCHASE_AGREEMENT = 'IHRP';
	const INSTALLMENT = 'INSM';
	const INVOICE_PAYMENT = 'IVPT';
	const MULTI_CURRENY_CHEQUE_DOMESTIC = 'MCDM';
	const MULTI_CURRENY_CHEQUE_FOREIGN = 'MCFG';
	const MULTIPLE_SERVICE_TYPES = 'MSVC';
	const NOT_OTHERWISE_SPECIFIED = 'NOWS';
	const ORDER_CHEQUE_DOMESTIC = 'OCDM';
	const ORDER_CHEQUE_FOREIGN = 'OCFG';
	const OPENING_FEE = 'OFEE';
	const OTHER = 'OTHR';
	const PREAUTHORIZED_DEBIT = 'PADD';
	const PAYMENT_TERMS = 'PTSP';
	const REPRESENTED_CHECK_ENTRY = 'RCKE';
	const RECEIPT_PAYMENT = 'RCPT';
	const REBATE = 'REBT';
	const REFUND = 'REFU';
	const RENT = 'RENT';
	const ACCOUNT_OVERDRAFT_REPAYMENT = 'REOD';
	const REIMBURSEMENT_OF_A_PREVIOUS_ERRONEOUS_TRANSACTION = 'RIMB';
	const BILATERAL_REPO_INTERNET_NETTING = 'RPNT';
	const ROUND_ROBIN = 'RRBN';
	const RECEIVE_AGAINST_PAYMENT = 'RVPM';
	const PAYMENT_SLIP_INSTRUCTION = 'SLPI';
	const SPLIT_PAYMENTS = 'SPLT';
	const STUDY = 'STDY';
	const TBA_PAIROFF_NETTING = 'TBAN';
	const TELECOMMUNICATIONS_BILL = 'TBIL';
	const TOWN_COUNCIL_SERVICE_CHARGES = 'TCSC';
	const TELEPHONE_INITIATED_TRANSACTION = 'TELI';
	const TMPG_CLAIM_PAYMENT = 'TMPG';
	const TRI_PARTY_REPO_INTEREST = 'TPRI';
	const TRIPARTY_REPO_NETTING = 'TPRP';
	const TRUNCATED_PAYMENT_SLIP = 'TRNC';
	const TRAVELLER_CHEQUE = 'TRVC';
	const INTERNET_INITIATED_TRANSACTION = 'WEBI';

	// Instant Payments
	const INSTANT_PAYMENTS = 'IPAY';
	const INSTANT_PAYMENTS_CANCELLATION = 'IPCA';
	const INSTANT_PAYMENTS_FOR_DONATIONS = 'IPDO';
	const INSTANT_PAYMENTS_IN_E_COMMERCE_WITHOUT_ADDRESS_DATA = 'IPEA';
	const INSTANT_PAYMENTS_IN_E_COMMERCE_WITH_ADDRESS_DATA = 'IPEC';
	const INSTANT_PAYMENTS_IN_E_COMMERCE = 'IPEW';
	const INSTANT_PAYMENTS_AT_POS = 'IPPS';
	const INSTANT_PAYMENTS_RETURN = 'IPRT';
	const INSTANT_PAYMENTS_UNATTENDED_VENDING_MACHINE_WITH_FA = 'IPU2';
	const INSTANT_PAYMENTS_UNATTENDED_VENDING_MACHINE_WITHOUT_FA = 'IPUW';

	// Investment
	const ANNUITY = 'ANNI';
	const CUSTODIAN_MANAGEMENT_FEE_INHOUSE = 'CAFI';
	const CAPITAL_FALLING_DUE_INHOUSE = 'CFDI';
	const COMMODITY_TRANSFER = 'CMDT';
	const DERIVATIVES = 'DERI';
	const DIVIDEND = 'DIVD';
	const FOREIGN_EXCHANGE = 'FREX';
	const HEDGING = 'HEDG';
	const INVESTMENT_SECURITIES = 'INVS';
	const PRECIOUS_METAL = 'PRME';
	const SAVINGS = 'SAVG';
	const SECURITIES = 'SECU';
	const SECURITIES_PURCHASE_INHOUSE = 'SEPI';
	const TREASURY_PAYMENT = 'TREA';
	const UNIT_TRUST_PURCHASE = 'UNIT';

	// Listed Derivatives
	const FUTURES_NETTING_PAYMENT = 'FNET';
	const FUTURES = 'FUTR';

	// Medical
	const ANESTHESIA_SERVICES = 'ANTS';
	const CONVALESCENT_CARE_FACILITY = 'CVCF';
	const DURABLE_MEDICALE_EQUIPMENT = 'DMEQ';
	const DENTAL_SERVICES = 'DNTS';
	const HOME_HEALTH_CARE = 'HLTC';
	const HEALTH_INSURANCE = 'HLTI';
	const HOSPITAL_CARE = 'HSPC';
	const INTERMEDIATE_CARE_FACILITY = 'ICRF';
	const LONG_TERM_CARE_FACILITY = 'LTCF';
	const MEDICAL_AID_FUND_CONTRIBUTION = 'MAFC';
	const MEDICAL_AID_REFUND = 'MARF';
	const MEDICAL_SERVICES = 'MDCS';
	const VISION_CARE = 'VIEW';

	// OTC Derivatives
	const CREDIT_DEFAULT_EVENT_PAYMENT = 'CDEP';
	const SWAP_CONTRACT_FINAL_PAYMENT = 'SWFP';
	const SWAP_CONTRACT_PARTIAL_PAYMENT = 'SWPP';
	const SWAP_CONTRACT_RESET_PAYMENT = 'SWRS';
	const SWAP_CONTRACT_UPFRONT_PAYMENT = 'SWUF';

	// Salary & Benefits
	const ADVISORY_DONATION_COPYRIGHT_SERVICES = 'ADCS';
	const ACTIVE_EMPLOYMENT_POLICY = 'AEMP';
	const ALLOWANCE = 'ALLW';
	const ALIMONY_PAYMENT = 'ALMY';
	const BABY_BONUS_SCHEME = 'BBSC';
	const CHILD_BENEFIT = 'BECH';
	const UNEMPLOYMENT_DISABILITY_BENEFIT = 'BENE';
	const BONUS_PAYMENT = 'BONU';
	const CASH_COMPENSATION_HELPLESSNESS_DISABILITY = 'CCHD';
	const COMMISSION = 'COMM';
	const COMPANY_SOCIAL_LOAN_PAYMENT_TO_BANK = 'CSLP';
	const GUARANTEE_FUND_RIGHTS_PAYMENT = 'GFRP';
	const AUSTRIAN_GOVERNMENT_EMPLOYEES_CATEGORY_A = 'GVEA';
	const AUSTRIAN_GOVERNMENT_EMPLOYEES_CATEGORY_B = 'GVEB';
	const AUSTRIAN_GOVERNMENT_EMPLOYEES_CATEGORY_C = 'GVEC';
	const AUSTRIAN_GOVERNMENT_EMPLOYEES_CATEGORY_D = 'GVED';
	const GOVERMENT_WAR_LEGISLATION_TRANSFER = 'GWLT';
	const HOUSING_RELATED_CONTRIBUTION = 'HREC';
	const PAYROLL = 'PAYR';
	const PENSION_FUND_CONTRIBUTION = 'PEFC';
	const PENSION_PAYMENT = 'PENS';
	const PRICE_PAYMENT = 'PRCP';
	const REHABILITATION_SUPPORT = 'RHBS';
	const SALARY_PAYMENT = 'SALA';
	const SOCIAL_SECURITY_BENEFIT = 'SSBE';

	// Securities Lending
	const LENDING_BUY_IN_NETTING = 'LBIN';
	const LENDING_CASH_COLLATERAL_FREE_MOVEMENT = 'LCOL';
	const LENDING_FEES = 'LFEE';
	const LENDING_EQUITY_MARKEDTOMARKET_CASH_COLLATERAL = 'LMEQ';
	const LENDING_FIXED_INCOME_MARKEDTOMARKET_CASH_COLLATERAL = 'LMFI';
	const LENDING_UNSPECIFIED_TYPE_OF_MARKEDTOMARKET_CASH_COLLATERAL = 'LMRK';
	const LENDING_REBATE_PAYMENTS = 'LREB';
	const LENDING_REVENUE_PAYMENTS = 'LREV';
	const LENDING_CLAIM_PAYMENT = 'LSFL';

	// Tax
	const ESTATE_TAX = 'ESTX';
	const FOREIGN_WORKER_LEVY = 'FWLV';
	const GOODS_SERVICES_TAX = 'GSTX';
	const HOUSING_TAX = 'HSTX';
	const INCOME_TAX = 'INTX';
	const NET_INCOME_TAX = 'NITX';
	const PROPERTY_TAX = 'PTXP';
	const ROAD_TAX = 'RDTX';
	const TAX_PAYMENT = 'TAXS';
	const VALUE_ADDED_TAX_PAYMENT = 'VATX';
	const WITH_HOLDING = 'WHLD';

	// Tax 
	const TAX_REFUND = 'TAXR';

	// Trailer Fee
	const TRAILER_FEE_PAYMENT = 'B112';
	const TRAILER_FEE_REBATE = 'BR12';
	const NON_US_MUTUAL_FUND_TRAILER_FEE_PAYMENT = 'TLRF';
	const NON_US_MUTUAL_FUND_TRAILER_FEE_REBATE_PAYMENT = 'TLRR';

	// Transport
	const AIR = 'AIRB';
	const BUS = 'BUSB';
	const FERRY = 'FERB';
	const RAILWAY = 'RLWY';
	const ROAD_PRICING = 'TRPT';

	// Utilities
	const CABLE_TVBILL = 'CBTV';
	const ELECTRICITY_BILL = 'ELEC';
	const ENERGIES = 'ENRG';
	const GAS_BILL = 'GASB';
	const NETWORK_CHARGE = 'NWCH';
	const NETWORK_COMMUNICATION = 'NWCM';
	const OTHER_TELECOM_RELATED_BILL = 'OTLC';
	const TELEPHONE_BILL = 'PHON';
	const UTILITIES = 'UBIL';
	const WATER_BILL = 'WTER';
}
