name: BC Check
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  bc_check:
    name: Backwards Compatibility Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install BC checker
        run: composer require --dev roave/backward-compatibility-check
      - name: Check for BC breaks
        run: vendor/bin/roave-backward-compatibility-check
